---
title: "GetPhenoTrialDataFromT3"
author: "Jean-Luc Jannink and David Waring"
date: "2023-07-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Use here and BrAPI helper
```{r libraries}
packages_used <- c("tidyverse", "devtools", "BrAPI")
ip <- installed.packages()
all_packages_installed <- TRUE
for (package in packages_used){
  if (!(package %in% ip[,"Package"])){
    print(paste("Please install package", package))
    all_packages_installed <- FALSE
  }
}#END packages_used
if (!all_packages_installed) stop("Need to install packages")
# Run this code if you need to install BrAPI
if (!("BrAPI" %in% ip[,"Package"])){
  devtools::install_git("https://github.com/TriticeaeToolbox/BrAPI.R")
}
library(tidyverse)
library(devtools)
library(BrAPI)

listBrAPIConnections()
brapi <- getBrAPIConnection("T3/Wheat")

here::i_am("code/GetPhenoTrialDataWithBrAPI.Rmd")
```

## Function to get a phenotypic study from a BrAPI server
```{r get a study}
getStudy <- function(studyName, traits=NULL){
  studyMeta <- brapi$get("studies",
                         query=list(studyName=studyName))
  studyDbId <- studyMeta$data[[1]]$studyDbId

  plots <- brapi$get("observationunits",
                     query=list(studyDbId=studyDbId),
                     page="all", pageSize=100)
  plot_info <- list()
  for (plot in plots$combined_data) {
    info <- list(
      id = plot$observationUnitDbId,
      row = plot$observationUnitPosition$positionCoordinateY,
      col = plot$observationUnitPosition$positionCoordinateX
    )
    # this is where plot (number), replicate, and block are held
    for (olr in plot$observationUnitPosition$observationLevelRelationships) {
      info[[olr$levelName]] <- olr$levelCode
    }
    plot_info[[plot$observationUnitName]] <- info
  }

  study <- brapi$get("observations", 
                     query=list(studyDbId=studyDbId),
                     page="all", pageSize=500)
  phenoDat <- study$combined_data
  
  toRet <- dplyr::tibble()
  addToTib <- function(pDl){
    toRet <<- dplyr::bind_rows(
      toRet,
      c(studyName=studyName,
        pDl[c("observationUnitName",
              "germplasmName",
              "observationVariableName",
              "value")],
        plotNumber=plot_info[[pDl$observationUnitName]]$plot,
        replicate=plot_info[[pDl$observationUnitName]]$replicate,
        block=plot_info[[pDl$observationUnitName]]$block,
        row=plot_info[[pDl$observationUnitName]]$row,
        col=plot_info[[pDl$observationUnitName]]$col))
  }
  d <- sapply(phenoDat, addToTib)
  toRet <- toRet %>% arrange(plotNumber)
  
  if (!is.null(traits)){
    toKeep <- NULL
    for (trait in traits){
      toKeep <- union(toKeep, grep(trait, toRet$observationVariableName))
    }
    toRet <- dplyr::slice(toRet, sort(toKeep))
  }
  return(toRet)
}
```

## Get phenotypic data from T3 using BrAPI
After this `allPhenoData` is a long tibble with yield, test weight, and height
```{r assemble studies}
studies <- c("YldQtl-Val_2014_ClayCenter",
             "YldQtl-Val_2014_Lincoln",
             "YldQtl-Val_2014_Mead",
             "YldQtl-Val_2014_Sidney")
allPhenoData <- tibble()

for (studyName in studies){
  oneTrial <- getStudy(studyName, traits=c("yield", "height", "weight"))
  allPhenoData <- dplyr::bind_rows(allPhenoData, oneTrial)
}
readr::write_csv(allPhenoData, 
                 here::here("data", "multitrialPhenoDataBrAPI.csv"))

nTrials <- allPhenoData$studyName %>% unique %>% length
nAccessions <- allPhenoData$germplasmName %>% unique %>% length
nTraits <- allPhenoData$observationVariableName %>% unique %>% length
nYieldPlots <- grep("yield", allPhenoData$observationVariableName) %>% length
nHeightPlots <- grep("height", allPhenoData$observationVariableName) %>% length
nTestWPlots <- grep("test", allPhenoData$observationVariableName) %>% length

phenoInfo <- tibble(variable=c("nTrials", "nAccessions", "nTraits", 
                               "nYieldPlots", "nHeightPlots", "nTestWPlots"),
                    value=c(nTrials, nAccessions, nTraits, 
                            nYieldPlots, nHeightPlots, nTestWPlots))
phenoInfo  %>% rmarkdown::paged_table()
```
