---
title: "combined analysis using after the spatial correction using sommer"
author: "Tesfahun A. Setotaw"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# data import and cleaning 
# set the working directory 
setwd("/Users/tas286/Documents/GitHub/spatial_analysis")
list.files()
df = read.csv("data/phenotype.csv")
head(df)
# identify factor variables and change to factor
library(metan)

df = as_factor(.data = df, c(studyYear,locationName, germplasmName,replicate, blockNumber))
df$R = as.factor(df$rowNumber)
df$C = as.factor(df$colNumber)
str(df)

## Summarise the data

summary(df)
library(dplyr)
library(ggplot2)
colnames(df)
colnames(df)[31] = "Gr_protein"
colnames(df)[32] = "test_weight"
colnames(df)[33] = "Yield"
df %>% group_by(germplasmName,locationName) %>% summarize_at(.vars = "Yield", .funs = c(min,max,mean))
ggplot(df) +
  geom_boxplot(mapping = aes(x = germplasmName, y = Yield)) +
  facet_grid("locationName")

out = boxplot.stats(df$Yield)$out
out_ind <- which(df$Yield %in% c(out))
out_ind
df1 = df
# analysis using lme4 package 
df1 <- df1[order(df1$locationName,df1$colNumber,df1$rowNumber),] # to reorder the row and column

# Standard file name for the script and factor variables 
met = df1
met$geno = met$germplasmName
met$rep = met$replicate
met$C  = met$C
met$R = met$R
met$col = met$colNumber
met$row = met$rowNumber
met$block = met$blockNumber
met$env = met$studyYear:met$locationName
met$env  = gsub(pattern = ":", replacement = "_", x = met$env)
met$env =as.factor(met$env)
```

```{r}
# spatial analysis over location trials
# List of traits to be analyze 
Traits <- c("Yield", "Gr_protein","test_weight")

# Combine the train mean output in one data file
Mean_Aurora_2022 = as.data.frame(Result.Mean_spats_sp_BLUP$`2022_Aurora, SD`)
Mean_Aurora_2022$env =  "Aurora_2022" # add the column with envt name 
Mean_Aurora_2022$geno = rownames(Mean_Aurora_2022)
Mean_Dakota_2022 = as.data.frame(Result.Mean_spats_sp_BLUP$`2022_Dakota Lakes, SD`)
Mean_Dakota_2022$env = "Dakota_2022"
Mean_Dakota_2022$geno = rownames(Mean_Dakota_2022)
Mean_Winner_2022 = as.data.frame(Result.Mean_spats_sp_BLUP$`2022_Winner, SD`)
Mean_Winner_2022$env = "Winner_2022"
Mean_Winner_2022$geno = rownames(Mean_Winner_2022)
head(Mean_Aurora_2022)

#Combine all the data in a single dataframe
dfcomb = rbind(Mean_Aurora_2022,Mean_Dakota_2022,Mean_Winner_2022)
#####################################################
# change factor variables to factor
met.comb = dfcomb
met.comb$geno = as.factor(met.comb$geno)
met.comb$env = as.factor(met.comb$env)

#r = length(levels(met.comb$rep))
Env<-levels(met.comb$env)
ne<-length(levels(met.comb$env)) # the number of the environment year:loc or location
nt<-length(Traits) # number of traits 
#Create matrix to store the heritability 
Result_comb_mean_sp.h2 <- matrix(nrow = 1, ncol = nt) # the matrix to put the h2
colnames(Result_comb_mean_sp.h2) <- Traits
rownames(Result_comb_mean_sp.h2) <- "Combined"
#####


library(sommer)

# subseting the traits with NA vlaue less than 25
TraitN = colnames(met.comb[Traits])[colSums(is.na(met.comb[Traits])) < 25] # selecting the trait without NA
  ntt = length((TraitN))
  gen = length(levels(met.comb$geno))
  ## Creat matrix to store the mean data 
  MAT <- matrix(nrow = gen, ncol = ntt) # create matrix based on the number of traits
  colnames(MAT)<- TraitN # name the column using the trait name
  rownames(MAT) <- sort(levels(met.comb$geno)) # name the row using the genotype name 
  
  for (Trait in TraitN){
    eval(parse(text = paste("mixcomb = mmer(",Trait," ~ 1,
                            random = ~ geno + env + geno:env,
                            rcov = ~units,
                            data = met.comb,
                            tolParConv = 1e-6, verbose = FALSE)")))
  
    svscomb = summary(mixcomb)
    sspcomb<-data.frame(svscomb$varcomp)
    rownames(sspcomb) <- c("geno", "env", "geno:env", "Residual")
     v.e1 <-sspcomb["Residual", "VarComp"]
     v.g1 <-sspcomb["geno", "VarComp"]
     v.ge <- sspcomb["geno:env","VarComp"]
    Result_comb_sp.h2[1,Trait]<- round(v.g1/(v.g1 + (v.ge/ne) + (v.e1/ne)),3)
    prsp = predict.mmer(mixcomb,classify = "geno")
    pmsp = prsp$pvals[,1:3]
    rownames(pmsp) = pmsp$geno
    ##Putting the mean data of the genotyeps in the matrix 
    for(name in levels(met$geno)){
    MAT[name,Trait] = pmsp[name,3]
    }

}

    

```

