---
title: "Single location spatial analysis using SpAts"
author: "Tesfahun A. Setotaw"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# data import and cleaning 
# set the working directory 
setwd("/Users/tas286/Documents/GitHub/spatial_analysis")
list.files()
df = read.csv("data/phenotype.csv")
head(df)
# identify factor variables and change to factor
library(metan)

df = as_factor(.data = df, c(studyYear,locationName, germplasmName,replicate, blockNumber))
df$R = as.factor(df$rowNumber)
df$C = as.factor(df$colNumber)
str(df)

## Summarise the data

summary(df)
library(dplyr)
library(ggplot2)
colnames(df)
colnames(df)[31] = "Gr_protein"
colnames(df)[32] = "test_weight"
colnames(df)[33] = "Yield"
df %>% group_by(germplasmName,locationName) %>% summarize_at(.vars = "Yield", .funs = c(min,max,mean))
ggplot(df) +
  geom_boxplot(mapping = aes(x = germplasmName, y = Yield)) +
  facet_grid("locationName")

out = boxplot.stats(df$Yield)$out
out_ind <- which(df$Yield %in% c(out))
out_ind
df1 = df
# analysis using lme4 package 
df1 <- df1[order(df1$locationName,df1$colNumber,df1$rowNumber),] # to reorder the row and column

# Standard file name for the script and factor variables 
met = df1
met$geno = met$germplasmName
met$rep = met$replicate
met$C  = met$C
met$R = met$R
met$col = met$colNumber
met$row = met$rowNumber
met$block = met$blockNumber
met$env = met$studyYear:met$locationName
met$env  = gsub(pattern = ":", replacement = "_", x = met$env)
met$env =as.factor(met$env)
```

```{r - single experiment/location spatial analysis using SpAts}

# List of traits to be analyze 
Traits <- c("Yield", "Gr_protein","test_weight")

# The number and levels of factor varialbes
r = length(levels(met$rep)) # the number of replication 
Env<-levels(met$env) # the levels of Environment 
ne<-length(levels(met$env)) # the number of the environment year:loc or location
nt<-length(Traits) # number of traits 

####################################################
# creating list or matrix to store the output data 
####################################################
Result_spats_sp.h2 <- matrix(nrow = ne, ncol = nt) # the matrix to put the h2
colnames(Result_spats_sp.h2) <- Traits # name the column using Trait names
rownames(Result_spats_sp.h2) <- Env # name the rows using Environment names
#####

# The BLUP mean
Result.Mean_spats_sp_BLUP <- vector(mode = "list", length = length(Env)) #length(levels(met.fbn$env)))
names(Result.Mean_spats_sp_BLUP) <- Env



# Defining the spat analysis formula 
nseg1 = length(levels(met$R)) # the numbre of the rows
nseg2 = length(levels(met$C)) # the number of the columns
spatial.SpATS <- as.formula(~ PSANOVA(col, row, 
                                      nseg = c(nseg1, nseg2), 
                                      degree = 3, pord = 2,
                                      nest.div = 2))

library(SpATS) # load the package SpATs
#The main analysis 
system.time(
for (i in 1:ne){
  SL <- droplevels(subset(x = met, subset = env == Env[i]) )# Subseting the data for each env
  TraitN = colnames(SL[Traits])[colSums(is.na(SL[Traits])) < 25] # selecting the trait without NA
  ntt = length((TraitN))
  gen = length(levels(SL$geno))
  MAT <- matrix(nrow = gen, ncol = ntt) # create matrix based on the number of traits
  colnames(MAT)<- TraitN
  rownames(MAT) <- sort(levels(SL$geno))
  
  for (Trait in TraitN){
    tr = "Trait"
    geno = "geno"
    eval(parse(text = paste("mixspat = SpATS(response = ",tr,", 
                             spatial = spatial.SpATS, 
                             genotype = geno, genotype.as.random = TRUE, fixed = NULL, 
                             random = ~ C + R + rep, data = SL, 
                             control =  list(tolerance = 1e-03))")))
    
    # svspat = as.data.frame(summary(mixspat, which = "variances"))
   
    Result_spats_sp.h2[i,Trait]<- getHeritability(mixspat)
  
    pred = predict(mixspat, which = "geno")
    geno_mean = pred %>% group_by(geno) %>%
               summarise_at(.vars = "predicted.values", .funs = mean)
    geno_mean = as.data.frame(geno_mean)
    rownames(geno_mean) <- geno_mean$geno
     for(name in levels(SL$geno)){
    MAT[name,Trait] = geno_mean[name,2]
    }
  ##heatmap plot for the spatial analysis in row column

  plot(mixspat, main = paste0(Trait))
  plot(variogram(mixspat))
}
##Putting the mean data of the genotyeps in the matrix 
  Result.Mean_spats_sp_BLUP[[i]] = MAT
}
)
```
