---
title: "Data cleaning"
author: "Tesfahun A. Setotaw"
date: "2023-02-28"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, 
                      tidy='styler', tidy.opts=list(strict=FALSE,width.cutoff=100), highlight=TRUE)
```

```{r data cleaning and preparation}
# data import and cleaning 
# set the working directory 
setwd("/Users/tas286/Documents/GitHub/spatial_analysis")
list.files()
df = read.csv("data/phenotype.csv")
head(df)
# identify factor variables and change to factor
library(metan)

df = as_factor(.data = df, c(studyYear,locationName, germplasmName,replicate, blockNumber))
df$R = as.factor(df$rowNumber)
df$C = as.factor(df$colNumber)
str(df)

## Summarise the data

summary(df)
library(dplyr)
library(ggplot2)
colnames(df)
colnames(df)[31] = "Gr_protein"
colnames(df)[32] = "test_weight"
colnames(df)[33] = "Yield"
df %>% group_by(germplasmName,locationName) %>% summarize_at(.vars = "Yield", .funs = c(min,max,mean))
ggplot(df) +
  geom_boxplot(mapping = aes(x = germplasmName, y = Yield)) +
  facet_grid("locationName")

out = boxplot.stats(df$Yield)$out
out_ind <- which(df$Yield %in% c(out))
out_ind
df1 = df
# analysis using lme4 package 
df1 <- df1[order(df1$locationName,df1$colNumber,df1$rowNumber),] # to reorder the row and column

# Standard file name for the script and factor variables 
met = df1
met$geno = met$germplasmName
met$rep = met$replicate
met$C  = met$C
met$R = met$R
met$col = met$colNumber
met$row = met$rowNumber
met$block = met$blockNumber
met$env = met$studyYear:met$locationName
met$env  = gsub(pattern = ":", replacement = "_", x = met$env)
met$env =as.factor(met$env)

```
