---
title: "Single location anlalysis with spatial correction using sommer"
author: "Tesfahun A. Setotaw"
date: "2023-02-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
# data import and cleaning 
# set the working directory 
setwd("/Users/tas286/Documents/GitHub/spatial_analysis")
list.files()
met = read.csv("data/phenotype.csv")
head(met)
# Define the factor variables and change to factor
met$geno = met$germplasmName
met$rep = met$replicate
met$C  = met$C
met$R = met$R
met$col = met$colNumber
met$row = met$rowNumber
met$block = met$blockNumber
met$env = met$studyYear:met$locationName
met$env  = gsub(pattern = ":", replacement = "_", x = met$env)
met$env =as.factor(met$env)
## Summarise the data

summary(df)
library(dplyr)
library(ggplot2)
colnames(df)
colnames(df)[31] = "Gr_protein"
colnames(df)[32] = "test_weight"
colnames(df)[33] = "Yield"
df %>% group_by(germplasmName,locationName) %>% summarize_at(.vars = "Yield", .funs = c(min,max,mean))
ggplot(df) +
  geom_boxplot(mapping = aes(x = germplasmName, y = Yield)) +
  facet_grid("locationName")
########################
# removing outlier
########################
out = boxplot.stats(df$Yield)$out
out_ind <- which(df$Yield %in% c(out))
out_ind
##### Sort the data by location, col and row
met <- met[order(met$loc,df1$col,df1$row),] # to reorder the row and column


```

```{r - Spatial analyis using Sommer package}
# The list of traits to be analyzed 
Traits <- c("Yield", "Gr_protein","test_weight") 

# length of the factor variables
#################################
r = length(levels(met$rep)) # number of replications
Env<-levels(met$env) # the number of environement 
ne<-length(levels(met$env)) # the number of the environment year:loc or location
nt<-length(Traits) # number of traits 

##########################################################
# Define the list and matrix to store the analysis output 
############################################################

#Heritability 
Result_sommer_sp.h2 <- matrix(nrow = ne, ncol = nt) # the matrix to put the h2
colnames(Result_sommer_sp.h2) <- Traits # naming the columns 
rownames(Result_sommer_sp.h2) <- Env # naming the row of the matrix 

# Define the list to put the BLUP mean value for each environment 

Result.Mean_sommer_sp_BLUP <- vector(mode = "list", length = length(Env)) #length(levels(met.fbn$env)))
names(Result.Mean_sommer_sp_BLUP) <- Env

# Package used for analysis 
library(sommer)

system.time(for (i in 1:ne){
  SL <- droplevels(subset(x = met, subset = env == Env[i]) )# Subseting the data for each env
  TraitN = colnames(SL[Traits])[colSums(is.na(SL[Traits])) < 25] # selecting the trait without NA
  ntt = length((TraitN))
  gen = length(levels(SL$geno))
  MAT <- matrix(nrow = gen, ncol = ntt) # create matrix based on the number of traits
  colnames(MAT)<- TraitN
  rownames(MAT) <- sort(levels(SL$geno))
  
  for (Trait in TraitN){
    eval(parse(text = paste("mixsp = mmer(",Trait," ~ 1,
                            random = ~ geno + rep + R+C+spl2Da(col,row),
                            rcov = ~units,
                            data = SL,
                            tolParConv = 1e-6, verbose = FALSE)")))
  
    svsp = summary(mixsp)
    ssp1<-data.frame(svsp$varcomp)
    rownames(ssp1) <- c("geno", "rep", "row", "col", "A:all", "Residual")
     v.e1 <-ssp1["Residual", "VarComp"]
     v.g1 <-ssp1["geno", "VarComp"]
     Result_sommer_sp.h2[i,Trait]<- round(v.g1/(v.g1 + v.e1/r),3)
     
     #########################################
     # Predict mean using fitted value
     #########################################
     
     fit = fitted(mixsp)
     head(fitval)
     fitval = fit$dataWithFitted # the data with fitted value
     
     fitval$AdjMean = fitval[,paste0(Trait,".fitted")]- fitval[,"C.fitted"] -
       fitval[,"R.fitted"] - fitval[,"rep.fitted"]- fitval[,"A:all.fitted"]

      adjMean = fitval %>% group_by(geno) %>% summarise_at(.vars = "AdjMean",
                                                         .funs = mean)
     adjMean = as.data.frame(adjMean)
     rownames(adjMean) = adjMean$geno
     
     ####################################################
     # To be used in case- it required more processing time 
     #######################################################
    # prsp = predict(mixsp,classify = "geno")
    # pmsp = prsp$pvals[,1:3]
    # rownames(pmsp) = pmsp$geno

  ##Putting the mean data of the genotyeps in the matrix 
    for(name in seq(levels(SL$geno))){
    MAT[name,Trait] = adjMean[name,2]
    }
    
}

  Result.Mean_sommer_sp_BLUP[[i]] = MAT
}
)
Result.Mean_sommer_sp_BLUP$`2022_Winner, SD`
```

